=== Filip-Dvorak/XML/schema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
    targetNamespace="urn:vse:dvof01:kalendarSoutezi"
    xmlns="urn:vse:dvof01:kalendarSoutezi"
    xmlns:ks="rn:vse:dvof01:kalendarSoutezi"
    elementFormDefault="qualified">
    
    
    <xs:element name="kalendar_soutezi" type="kalendarSouteziType">
        
    </xs:element>
    
    
    <xs:complexType name="kalendarSouteziType">
        <xs:sequence>
            <xs:element name="pary" type="paryType">
                <xs:unique name="uniqueParID">
                    <xs:selector xpath="ks:par"></xs:selector>
                    <xs:field xpath="@id"></xs:field>
                </xs:unique>
            </xs:element>
            <xs:element name="soutez" type="soutezType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="paryType">
        <xs:sequence>
            <xs:element name="par" type="parType" maxOccurs="unbounded">
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="parType">
        <xs:sequence>
            <xs:element name="trida" type="vykonostniTridaType"></xs:element>
            <xs:element name="partner" type="partnerType"  />
            <xs:element name="partnerka" type="partnerType"  />
            <xs:element name="klub" type="klubType" />
        </xs:sequence>
        <xs:attribute name="id" type="idType" use="required"/>
    </xs:complexType>
    
    <xs:complexType name="klubType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="divize" type="xs:string" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>
    
    <xs:simpleType name="idType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>
    
    <xs:complexType name="partnerType">
        <xs:sequence>
            <xs:element name="idt" type="idType" />
            <xs:element name="jmeno" type="xs:string" />
            <xs:element name="prijmeni" type="xs:string" />
            <xs:element name="datum_narozeni" type="xs:date" />
            <xs:element name="email" type="emailType" />
            <xs:element name="foto" type="fotoType" >
            </xs:element>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="fotoType">
        <xs:attribute name="src" type="xs:string" use="required"/>
    </xs:complexType>
    
    <xs:simpleType name="emailType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[^@]+@[^@]+\.[^@]+"/>
        </xs:restriction>
    </xs:simpleType>
    
    
    <xs:complexType name="soutezType">
        <xs:sequence>
            <xs:element name="nazev" type="xs:string" />
            <xs:element name="datum" type="xs:date" />
            <xs:element name="adresa" type="adresaType" />
            <xs:element name="harmonogram" type="harmonogramType" />
            <xs:element name="termin_prihlaseni" type="xs:dateTime" />
            <xs:element name="porota" type="porotaType" />
            <xs:element name="kategorie" type="kategorieType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="adresaType">
        <xs:sequence>
            <xs:element name="lokace" type="xs:string"/>
            <xs:element name="ulice" type="xs:string"/>
            <xs:element name="cislo_popisne" type="xs:int"/>
            <xs:element name="mesto" type="xs:string"/>
            <xs:element name="psc" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="harmonogramType">
        <xs:sequence>
            <xs:element name="cas_otevreni_salu" type="xs:time"/>
            <xs:element name="cas_zahajeni_souteze" type="xs:time"/>
            <xs:element name="cas_konce_souteze" type="xs:time"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="porotaType">
        <xs:sequence>
            <xs:element name="porotce" type="porotceType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="porotceType">
        <xs:sequence>
            <xs:element name="jmeno" type="xs:string"/>
            <xs:element name="prijmeni" type="xs:string"/>
            <xs:element name="mesto" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:complexType name="kategorieType">
        <xs:sequence>
            <xs:element name="vekova_kategorie" type="xs:string"/>
            <xs:element name="vykonostni_trida" type="vykonostniTridaType" minOccurs="0" maxOccurs="3"/>
            <xs:element name="disciplina" type="disciplinaType"/>
            <xs:element name="prihlasene_pary" type="prihlaseneParyType">
            </xs:element>
        </xs:sequence>
        <xs:attribute name="typ" type="xs:string" use="required"/>
    </xs:complexType>
    
    
    <xs:complexType name="prihlaseneParyType">
        <xs:sequence>
            <xs:element name="par_id" type="idType" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="disciplinaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="LAT"></xs:enumeration>
            <xs:enumeration value="STT"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
    <xs:simpleType name="vykonostniTridaType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="E"></xs:enumeration>
            <xs:enumeration value="D"></xs:enumeration>
            <xs:enumeration value="C"></xs:enumeration>
            <xs:enumeration value="B"></xs:enumeration>
            <xs:enumeration value="A"></xs:enumeration>
            <xs:enumeration value="M"></xs:enumeration>
        </xs:restriction>
    </xs:simpleType>
    
</xs:schema>

=== Filip-Dvorak/XML/ukazka-upraveno.xml
<?xml version="1.0" encoding="UTF-8"?>
<kalendar_soutezi xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:schemaLocation="urn:vse:dvof01:kalendarSoutezi schema.xsd"
 xmlns="urn:vse:dvof01:kalendarSoutezi">
    <pary>
        <par id="1">
            <trida>B</trida>
            <partner>
                <idt>111</idt>
                <jmeno>Radek</jmeno>
                <prijmeni>Hrádek</prijmeni>
                <datum_narozeni>2001-04-10</datum_narozeni>
                <email>radek.hradek@gmail.com</email>
                <foto src="radek.png"></foto>
            </partner>
            <partnerka>
                <idt>222</idt>
                <jmeno>Radka</jmeno>
                <prijmeni>Hrádková</prijmeni>
                <datum_narozeni>2002-04-10</datum_narozeni>
                <email>radka.hradkova@gmail.com</email>
                <foto src="radka.png"></foto>
            </partnerka>
            <klub divize="moravskoslezska">Starlight Dance Studio</klub>
        </par>
        <par id="2">
            <trida>A</trida>
            <partner>
                <idt>333</idt>
                <jmeno>Šimon</jmeno>
                <prijmeni>Dominik</prijmeni>
                <datum_narozeni>2002-02-20</datum_narozeni>
                <email>simon.dominik@gmail.com</email>
                <foto src="simon.png"></foto>
            </partner>
            <partnerka>
                <idt>444</idt>
                <jmeno>Dominika</jmeno>
                <prijmeni>Šimonová</prijmeni>
                <datum_narozeni>2003-10-10</datum_narozeni>
                <email>dominika.simonova@gmail.com</email>
                <foto src="dominika.png"></foto>
            </partnerka>
            <klub divize="stredoceska">Rhythm  Motion Dance Academy</klub>
        </par>
        <par id="3">
            <trida>B</trida>
            <partner>
                <idt>555</idt>
                <jmeno>Tomáš</jmeno>
                <prijmeni>Koláč</prijmeni>
                <datum_narozeni>2009-11-28</datum_narozeni>
                <email>tomas.kolac@gmail.com</email>
                <foto src="tomas.png"></foto>
            </partner>
            <partnerka>
                <idt>666</idt>
                <jmeno>Antonie</jmeno>
                <prijmeni>Buchtíková</prijmeni>
                <datum_narozeni>2009-03-05</datum_narozeni>
                <email>antonie.buchtikova@gmail.com</email>
                <foto src="antonie.png"></foto>
            </partnerka>
            <klub divize="prazska">Dance Fusion Academy</klub>
        </par>
        <par id="4">
            <trida>C</trida>
            <partner>
                <idt>666</idt>
                <jmeno>Jan</jmeno>
                <prijmeni>Hrouda</prijmeni>
                <datum_narozeni>1985-04-10</datum_narozeni>
                <email>jan.hrouda@gmail.com</email>
                <foto src="jan.png"></foto>
            </partner>
            <partnerka>
                <idt>777</idt>
                <jmeno>Jana</jmeno>
                <prijmeni>Hroudová</prijmeni>
                <datum_narozeni>1987-07-20</datum_narozeni>
                <email>jana.hroudova@gmail.com</email>
                <foto src="jana.png"></foto>
            </partnerka>
            <klub divize="jihoceska">LaStDance</klub>
        </par>
    </pary>
    <soutez>
        <nazev>Ostrava Open 2024</nazev>
        <datum>2024-04-20</datum>
        <adresa>
            <lokace>Ostravar Arena</lokace>
            <ulice>U Areny</ulice>
            <cislo_popisne>123</cislo_popisne>
            <mesto>Ostrava</mesto>
            <psc>243 01</psc>
        </adresa>
        <harmonogram>
            <cas_otevreni_salu>09:00:00</cas_otevreni_salu>
            <cas_zahajeni_souteze>10:00:00</cas_zahajeni_souteze>
            <cas_konce_souteze>20:00:00</cas_konce_souteze>
        </harmonogram>
        <termin_prihlaseni>2024-03-31T23:00:00</termin_prihlaseni>
        <porota>
            <porotce>
                <jmeno>Jan</jmeno>
                <prijmeni>Klement</prijmeni>
                <mesto>Ostrava</mesto>
            </porotce>
            <porotce>
                <jmeno>Petr</jmeno>
                <prijmeni>Zajíc</prijmeni>
                <mesto>Mirošovice</mesto>
            </porotce>
        </porota>
        <kategorie typ="poharova">
            <vekova_kategorie>Dospělí</vekova_kategorie>
            <vykonostni_trida>B</vykonostni_trida>
            <vykonostni_trida>A</vykonostni_trida>
            <vykonostni_trida>M</vykonostni_trida>
            <disciplina>LAT</disciplina>
            <prihlasene_pary>
                <par_id>1</par_id>
                <par_id>2</par_id>
            </prihlasene_pary>
        </kategorie>
        <kategorie typ="liga">
            <vekova_kategorie>Mládež</vekova_kategorie>
            <disciplina>STT</disciplina>
            <prihlasene_pary>
                <par_id>3</par_id>
            </prihlasene_pary>
        </kategorie>
    </soutez>
    <soutez>
        <nazev>Velká cena města Beroun</nazev>
        <datum>2024-07-15</datum>
        <adresa>
            <lokace>Kulturní dům Plzeňka</lokace>
            <ulice>Plzeňská</ulice>
            <cislo_popisne>456</cislo_popisne>
            <mesto>Beroun</mesto>
            <psc>765 22</psc>
        </adresa>
        <harmonogram>
            <cas_otevreni_salu>08:00:00</cas_otevreni_salu>
            <cas_zahajeni_souteze>09:30:00</cas_zahajeni_souteze>
            <cas_konce_souteze>17:00:00</cas_konce_souteze>
        </harmonogram>
        <termin_prihlaseni>2024-06-30T23:00:00</termin_prihlaseni>
        <porota>
            <porotce>
                <jmeno>Jaroslav</jmeno>
                <prijmeni>Ječmen</prijmeni>
                <mesto>Pardubice</mesto>
            </porotce>
            <porotce>
                <jmeno>Ludvík</jmeno>
                <prijmeni>Ječmínek</prijmeni>
                <mesto>Plzeň</mesto>
            </porotce>
        </porota>
        <kategorie typ="postupova">
            <vekova_kategorie>Senioři</vekova_kategorie>
            <vykonostni_trida>C</vykonostni_trida>
            <disciplina>STT</disciplina>
            <prihlasene_pary>
                <par_id>4</par_id>
            </prihlasene_pary>
        </kategorie>
    </soutez>
</kalendar_soutezi>
